# Use uma imagem Node.js com suporte a React
FROM node:14

# Crie e configure o diretório de trabalho
WORKDIR /app

# Copie o package.json e package-lock.json para o contêiner
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código-fonte para o contêiner
COPY . .

# Construa o aplicativo React
RUN npm run build

# Exponha a porta em que o aplicativo estará em execução
EXPOSE 3001

# Comando para iniciar o aplicativo
CMD ["npm", "start"]
