# Use uma imagem Node.js
FROM node:14

# Crie e configure o diretório de trabalho
WORKDIR /app

# Copie o package.json e package-lock.json para o contêiner
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código-fonte para o contêiner
COPY . .

# Exponha a porta em que o aplicativo estará em execução
EXPOSE 3000

# Comando para iniciar o aplicativo
CMD ["npm", "start"]